# Generated by Django 3.2.4 on 2021-06-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoHardware', models.CharField(max_length=20)),
                ('nombreHardware', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('anio_lanzamiento', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
