# Generated by Django 3.2.3 on 2021-07-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='anio_lanzamiento',
            field=models.IntegerField(verbose_name='Año lanzamiento'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='nombreHardware',
            field=models.CharField(max_length=20, verbose_name='Modelo del Hardware'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='tipoHardware',
            field=models.CharField(max_length=20, verbose_name='Tipo de Hardware'),
        ),
    ]
